// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE

#include <endian.h>
#include <fcntl.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

static long syz_open_dev(volatile long a0, volatile long a1, volatile long a2)
{
  if (a0 == 0xc || a0 == 0xb) {
    char buf[128];
    sprintf(buf, "/dev/%s/%d:%d", a0 == 0xc ? "char" : "block", (uint8_t)a1,
            (uint8_t)a2);
    return open(buf, O_RDWR, 0);
  } else {
    char buf[1024];
    char* hash;
    strncpy(buf, (char*)a0, sizeof(buf) - 1);
    buf[sizeof(buf) - 1] = 0;
    while ((hash = strchr(buf, '#'))) {
      *hash = '0' + (char)(a1 % 10);
      a1 /= 10;
    }
    return open(buf, a2, 0);
  }
}

uint64_t r[1] = {0xffffffffffffffff};

int main(void)
{
  syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
  syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
  syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
  intptr_t res = 0;
  memcpy((void*)0x20000080, "/dev/sg#\000", 9);
  res = -1;
  res = syz_open_dev(0x20000080, 0, 0x183002);
  if (res != -1)
    r[0] = res;
  syscall(__NR_ioctl, r[0], 0x2285, 0ul);
  *(uint64_t*)0x200000c0 = 0x20000040;
  memcpy((void*)0x20000040,
         "\x00\x02\x00\x00\x08\x00\x00\x00\x00\x00\x1b\x42\xd6\xaf\x7f\xa4\x00"
         "\x08\x00\x00\xb0\xfb\xff\xff\xff\x1f\xcf\x48\x8b\x76\x62\xb1\x69\xd0"
         "\x90\x53\x77\x6c\x33\x19\xd7\xaa\xcb\x98\x2b\x35\xf9\x5a",
         48);
  *(uint64_t*)0x200000c8 = 0x30;
  *(uint64_t*)0x200000d0 = 0x20000180;
  memcpy((void*)0x20000180,
         "\xc6\x03\x00\x00\x00\x05\x32\x00\x00\x13\x00\xff\xef\xff\xff\x84\x7f"
         "\xaf\x43\xa0\x57\x5f\xfe\x94\x2a\x97\xe6\x5d\x59\xfe\xfa\x44\x16\x27"
         "\xa7\x96\x3c\xe7\xff\x50\x61\x50\x3d\xf2\xbd\x79\x63",
         47);
  *(uint64_t*)0x200000d8 = 0x2f;
  syscall(__NR_writev, r[0], 0x200000c0ul, 2ul);
  return 0;
}
