// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE

#include <dirent.h>
#include <endian.h>
#include <errno.h>
#include <fcntl.h>
#include <setjmp.h>
#include <signal.h>
#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/ioctl.h>
#include <sys/mman.h>
#include <sys/mount.h>
#include <sys/prctl.h>
#include <sys/stat.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <time.h>
#include <unistd.h>

#include <linux/loop.h>

#ifndef __NR_memfd_create
#define __NR_memfd_create 319
#endif

static unsigned long long procid;

static void sleep_ms(uint64_t ms)
{
  usleep(ms * 1000);
}

static uint64_t current_time_ms(void)
{
  struct timespec ts;
  if (clock_gettime(CLOCK_MONOTONIC, &ts))
    exit(1);
  return (uint64_t)ts.tv_sec * 1000 + (uint64_t)ts.tv_nsec / 1000000;
}

static bool write_file(const char* file, const char* what, ...)
{
  char buf[1024];
  va_list args;
  va_start(args, what);
  vsnprintf(buf, sizeof(buf), what, args);
  va_end(args);
  buf[sizeof(buf) - 1] = 0;
  int len = strlen(buf);
  int fd = open(file, O_WRONLY | O_CLOEXEC);
  if (fd == -1)
    return false;
  if (write(fd, buf, len) != len) {
    int err = errno;
    close(fd);
    errno = err;
    return false;
  }
  close(fd);
  return true;
}

//% This code is derived from puff.{c,h}, found in the zlib development. The
//% original files come with the following copyright notice:

//% Copyright (C) 2002-2013 Mark Adler, all rights reserved
//% version 2.3, 21 Jan 2013
//% This software is provided 'as-is', without any express or implied
//% warranty.  In no event will the author be held liable for any damages
//% arising from the use of this software.
//% Permission is granted to anyone to use this software for any purpose,
//% including commercial applications, and to alter it and redistribute it
//% freely, subject to the following restrictions:
//% 1. The origin of this software must not be misrepresented; you must not
//%    claim that you wrote the original software. If you use this software
//%    in a product, an acknowledgment in the product documentation would be
//%    appreciated but is not required.
//% 2. Altered source versions must be plainly marked as such, and must not be
//%    misrepresented as being the original software.
//% 3. This notice may not be removed or altered from any source distribution.
//% Mark Adler    madler@alumni.caltech.edu

//% BEGIN CODE DERIVED FROM puff.{c,h}

#define MAXBITS 15
#define MAXLCODES 286
#define MAXDCODES 30
#define MAXCODES (MAXLCODES + MAXDCODES)
#define FIXLCODES 288

struct puff_state {
  unsigned char* out;
  unsigned long outlen;
  unsigned long outcnt;
  const unsigned char* in;
  unsigned long inlen;
  unsigned long incnt;
  int bitbuf;
  int bitcnt;
  jmp_buf env;
};
static int puff_bits(struct puff_state* s, int need)
{
  long val = s->bitbuf;
  while (s->bitcnt < need) {
    if (s->incnt == s->inlen)
      longjmp(s->env, 1);
    val |= (long)(s->in[s->incnt++]) << s->bitcnt;
    s->bitcnt += 8;
  }
  s->bitbuf = (int)(val >> need);
  s->bitcnt -= need;
  return (int)(val & ((1L << need) - 1));
}
static int puff_stored(struct puff_state* s)
{
  s->bitbuf = 0;
  s->bitcnt = 0;
  if (s->incnt + 4 > s->inlen)
    return 2;
  unsigned len = s->in[s->incnt++];
  len |= s->in[s->incnt++] << 8;
  if (s->in[s->incnt++] != (~len & 0xff) ||
      s->in[s->incnt++] != ((~len >> 8) & 0xff))
    return -2;
  if (s->incnt + len > s->inlen)
    return 2;
  if (s->outcnt + len > s->outlen)
    return 1;
  for (; len--; s->outcnt++, s->incnt++) {
    if (s->in[s->incnt])
      s->out[s->outcnt] = s->in[s->incnt];
  }
  return 0;
}
struct puff_huffman {
  short* count;
  short* symbol;
};
static int puff_decode(struct puff_state* s, const struct puff_huffman* h)
{
  int first = 0;
  int index = 0;
  int bitbuf = s->bitbuf;
  int left = s->bitcnt;
  int code = first = index = 0;
  int len = 1;
  short* next = h->count + 1;
  while (1) {
    while (left--) {
      code |= bitbuf & 1;
      bitbuf >>= 1;
      int count = *next++;
      if (code - count < first) {
        s->bitbuf = bitbuf;
        s->bitcnt = (s->bitcnt - len) & 7;
        return h->symbol[index + (code - first)];
      }
      index += count;
      first += count;
      first <<= 1;
      code <<= 1;
      len++;
    }
    left = (MAXBITS + 1) - len;
    if (left == 0)
      break;
    if (s->incnt == s->inlen)
      longjmp(s->env, 1);
    bitbuf = s->in[s->incnt++];
    if (left > 8)
      left = 8;
  }
  return -10;
}
static int puff_construct(struct puff_huffman* h, const short* length, int n)
{
  int len;
  for (len = 0; len <= MAXBITS; len++)
    h->count[len] = 0;
  int symbol;
  for (symbol = 0; symbol < n; symbol++)
    (h->count[length[symbol]])++;
  if (h->count[0] == n)
    return 0;
  int left = 1;
  for (len = 1; len <= MAXBITS; len++) {
    left <<= 1;
    left -= h->count[len];
    if (left < 0)
      return left;
  }
  short offs[MAXBITS + 1];
  offs[1] = 0;
  for (len = 1; len < MAXBITS; len++)
    offs[len + 1] = offs[len] + h->count[len];
  for (symbol = 0; symbol < n; symbol++)
    if (length[symbol] != 0)
      h->symbol[offs[length[symbol]]++] = symbol;
  return left;
}
static int puff_codes(struct puff_state* s, const struct puff_huffman* lencode,
                      const struct puff_huffman* distcode)
{
  static const short lens[29] = {3,  4,  5,  6,   7,   8,   9,   10,  11, 13,
                                 15, 17, 19, 23,  27,  31,  35,  43,  51, 59,
                                 67, 83, 99, 115, 131, 163, 195, 227, 258};
  static const short lext[29] = {0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2,
                                 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 0};
  static const short dists[30] = {
      1,    2,    3,    4,    5,    7,    9,    13,    17,    25,
      33,   49,   65,   97,   129,  193,  257,  385,   513,   769,
      1025, 1537, 2049, 3073, 4097, 6145, 8193, 12289, 16385, 24577};
  static const short dext[30] = {0, 0, 0,  0,  1,  1,  2,  2,  3,  3,
                                 4, 4, 5,  5,  6,  6,  7,  7,  8,  8,
                                 9, 9, 10, 10, 11, 11, 12, 12, 13, 13};
  int symbol;
  do {
    symbol = puff_decode(s, lencode);
    if (symbol < 0)
      return symbol;
    if (symbol < 256) {
      if (s->outcnt == s->outlen)
        return 1;
      if (symbol)
        s->out[s->outcnt] = symbol;
      s->outcnt++;
    } else if (symbol > 256) {
      symbol -= 257;
      if (symbol >= 29)
        return -10;
      int len = lens[symbol] + puff_bits(s, lext[symbol]);
      symbol = puff_decode(s, distcode);
      if (symbol < 0)
        return symbol;
      unsigned dist = dists[symbol] + puff_bits(s, dext[symbol]);
      if (dist > s->outcnt)
        return -11;
      if (s->outcnt + len > s->outlen)
        return 1;
      while (len--) {
        if (dist <= s->outcnt && s->out[s->outcnt - dist])
          s->out[s->outcnt] = s->out[s->outcnt - dist];
        s->outcnt++;
      }
    }
  } while (symbol != 256);
  return 0;
}
static int puff_fixed(struct puff_state* s)
{
  static int virgin = 1;
  static short lencnt[MAXBITS + 1], lensym[FIXLCODES];
  static short distcnt[MAXBITS + 1], distsym[MAXDCODES];
  static struct puff_huffman lencode, distcode;
  if (virgin) {
    lencode.count = lencnt;
    lencode.symbol = lensym;
    distcode.count = distcnt;
    distcode.symbol = distsym;
    short lengths[FIXLCODES];
    int symbol;
    for (symbol = 0; symbol < 144; symbol++)
      lengths[symbol] = 8;
    for (; symbol < 256; symbol++)
      lengths[symbol] = 9;
    for (; symbol < 280; symbol++)
      lengths[symbol] = 7;
    for (; symbol < FIXLCODES; symbol++)
      lengths[symbol] = 8;
    puff_construct(&lencode, lengths, FIXLCODES);
    for (symbol = 0; symbol < MAXDCODES; symbol++)
      lengths[symbol] = 5;
    puff_construct(&distcode, lengths, MAXDCODES);
    virgin = 0;
  }
  return puff_codes(s, &lencode, &distcode);
}
static int puff_dynamic(struct puff_state* s)
{
  static const short order[19] = {16, 17, 18, 0, 8,  7, 9,  6, 10, 5,
                                  11, 4,  12, 3, 13, 2, 14, 1, 15};
  int nlen = puff_bits(s, 5) + 257;
  int ndist = puff_bits(s, 5) + 1;
  int ncode = puff_bits(s, 4) + 4;
  if (nlen > MAXLCODES || ndist > MAXDCODES)
    return -3;
  short lengths[MAXCODES];
  int index;
  for (index = 0; index < ncode; index++)
    lengths[order[index]] = puff_bits(s, 3);
  for (; index < 19; index++)
    lengths[order[index]] = 0;
  short lencnt[MAXBITS + 1], lensym[MAXLCODES];
  struct puff_huffman lencode = {lencnt, lensym};
  int err = puff_construct(&lencode, lengths, 19);
  if (err != 0)
    return -4;
  index = 0;
  while (index < nlen + ndist) {
    int symbol;
    int len;
    symbol = puff_decode(s, &lencode);
    if (symbol < 0)
      return symbol;
    if (symbol < 16)
      lengths[index++] = symbol;
    else {
      len = 0;
      if (symbol == 16) {
        if (index == 0)
          return -5;
        len = lengths[index - 1];
        symbol = 3 + puff_bits(s, 2);
      } else if (symbol == 17)
        symbol = 3 + puff_bits(s, 3);
      else
        symbol = 11 + puff_bits(s, 7);
      if (index + symbol > nlen + ndist)
        return -6;
      while (symbol--)
        lengths[index++] = len;
    }
  }
  if (lengths[256] == 0)
    return -9;
  err = puff_construct(&lencode, lengths, nlen);
  if (err && (err < 0 || nlen != lencode.count[0] + lencode.count[1]))
    return -7;
  short distcnt[MAXBITS + 1], distsym[MAXDCODES];
  struct puff_huffman distcode = {distcnt, distsym};
  err = puff_construct(&distcode, lengths + nlen, ndist);
  if (err && (err < 0 || ndist != distcode.count[0] + distcode.count[1]))
    return -8;
  return puff_codes(s, &lencode, &distcode);
}
static int puff(unsigned char* dest, unsigned long* destlen,
                const unsigned char* source, unsigned long sourcelen)
{
  struct puff_state s = {
      .out = dest,
      .outlen = *destlen,
      .outcnt = 0,
      .in = source,
      .inlen = sourcelen,
      .incnt = 0,
      .bitbuf = 0,
      .bitcnt = 0,
  };
  int err;
  if (setjmp(s.env) != 0)
    err = 2;
  else {
    int last;
    do {
      last = puff_bits(&s, 1);
      int type = puff_bits(&s, 2);
      err = type == 0 ? puff_stored(&s)
                      : (type == 1 ? puff_fixed(&s)
                                   : (type == 2 ? puff_dynamic(&s) : -1));
      if (err != 0)
        break;
    } while (!last);
  }
  *destlen = s.outcnt;
  return err;
}

//% END CODE DERIVED FROM puff.{c,h}

#define ZLIB_HEADER_WIDTH 2

static int puff_zlib_to_file(const unsigned char* source,
                             unsigned long sourcelen, int dest_fd)
{
  if (sourcelen < ZLIB_HEADER_WIDTH)
    return 0;
  source += ZLIB_HEADER_WIDTH;
  sourcelen -= ZLIB_HEADER_WIDTH;
  const unsigned long max_destlen = 132 << 20;
  void* ret = mmap(0, max_destlen, PROT_WRITE | PROT_READ,
                   MAP_PRIVATE | MAP_ANON, -1, 0);
  if (ret == MAP_FAILED)
    return -1;
  unsigned char* dest = (unsigned char*)ret;
  unsigned long destlen = max_destlen;
  int err = puff(dest, &destlen, source, sourcelen);
  if (err) {
    munmap(dest, max_destlen);
    errno = -err;
    return -1;
  }
  if (write(dest_fd, dest, destlen) != (ssize_t)destlen) {
    munmap(dest, max_destlen);
    return -1;
  }
  return munmap(dest, max_destlen);
}

static int setup_loop_device(unsigned char* data, unsigned long size,
                             const char* loopname, int* loopfd_p)
{
  int err = 0, loopfd = -1;
  int memfd = syscall(__NR_memfd_create, "syzkaller", 0);
  if (memfd == -1) {
    err = errno;
    goto error;
  }
  if (puff_zlib_to_file(data, size, memfd)) {
    err = errno;
    goto error_close_memfd;
  }
  loopfd = open(loopname, O_RDWR);
  if (loopfd == -1) {
    err = errno;
    goto error_close_memfd;
  }
  if (ioctl(loopfd, LOOP_SET_FD, memfd)) {
    if (errno != EBUSY) {
      err = errno;
      goto error_close_loop;
    }
    ioctl(loopfd, LOOP_CLR_FD, 0);
    usleep(1000);
    if (ioctl(loopfd, LOOP_SET_FD, memfd)) {
      err = errno;
      goto error_close_loop;
    }
  }
  close(memfd);
  *loopfd_p = loopfd;
  return 0;

error_close_loop:
  close(loopfd);
error_close_memfd:
  close(memfd);
error:
  errno = err;
  return -1;
}

static void reset_loop_device(const char* loopname)
{
  int loopfd = open(loopname, O_RDWR);
  if (loopfd == -1) {
    return;
  }
  if (ioctl(loopfd, LOOP_CLR_FD, 0)) {
  }
  close(loopfd);
}

static long syz_mount_image(volatile long fsarg, volatile long dir,
                            volatile long flags, volatile long optsarg,
                            volatile long change_dir,
                            volatile unsigned long size, volatile long image)
{
  unsigned char* data = (unsigned char*)image;
  int res = -1, err = 0, need_loop_device = !!size;
  char* mount_opts = (char*)optsarg;
  char* target = (char*)dir;
  char* fs = (char*)fsarg;
  char* source = NULL;
  char loopname[64];
  if (need_loop_device) {
    int loopfd;
    memset(loopname, 0, sizeof(loopname));
    snprintf(loopname, sizeof(loopname), "/dev/loop%llu", procid);
    if (setup_loop_device(data, size, loopname, &loopfd) == -1)
      return -1;
    close(loopfd);
    source = loopname;
  }
  mkdir(target, 0777);
  char opts[256];
  memset(opts, 0, sizeof(opts));
  if (strlen(mount_opts) > (sizeof(opts) - 32)) {
  }
  strncpy(opts, mount_opts, sizeof(opts) - 32);
  if (strcmp(fs, "iso9660") == 0) {
    flags |= MS_RDONLY;
  } else if (strncmp(fs, "ext", 3) == 0) {
    bool has_remount_ro = false;
    char* remount_ro_start = strstr(opts, "errors=remount-ro");
    if (remount_ro_start != NULL) {
      char after = *(remount_ro_start + strlen("errors=remount-ro"));
      char before = remount_ro_start == opts ? '\0' : *(remount_ro_start - 1);
      has_remount_ro = ((before == '\0' || before == ',') &&
                        (after == '\0' || after == ','));
    }
    if (strstr(opts, "errors=panic") || !has_remount_ro)
      strcat(opts, ",errors=continue");
  } else if (strcmp(fs, "xfs") == 0) {
    strcat(opts, ",nouuid");
  }
  res = mount(source, target, fs, flags, opts);
  if (res == -1) {
    err = errno;
    goto error_clear_loop;
  }
  res = open(target, O_RDONLY | O_DIRECTORY);
  if (res == -1) {
    err = errno;
    goto error_clear_loop;
  }
  if (change_dir) {
    res = chdir(target);
    if (res == -1) {
      err = errno;
    }
  }

error_clear_loop:
  if (need_loop_device)
    reset_loop_device(loopname);
  errno = err;
  return res;
}

static void kill_and_wait(int pid, int* status)
{
  kill(-pid, SIGKILL);
  kill(pid, SIGKILL);
  for (int i = 0; i < 100; i++) {
    if (waitpid(-1, status, WNOHANG | __WALL) == pid)
      return;
    usleep(1000);
  }
  DIR* dir = opendir("/sys/fs/fuse/connections");
  if (dir) {
    for (;;) {
      struct dirent* ent = readdir(dir);
      if (!ent)
        break;
      if (strcmp(ent->d_name, ".") == 0 || strcmp(ent->d_name, "..") == 0)
        continue;
      char abort[300];
      snprintf(abort, sizeof(abort), "/sys/fs/fuse/connections/%s/abort",
               ent->d_name);
      int fd = open(abort, O_WRONLY);
      if (fd == -1) {
        continue;
      }
      if (write(fd, abort, 1) < 0) {
      }
      close(fd);
    }
    closedir(dir);
  } else {
  }
  while (waitpid(-1, status, __WALL) != pid) {
  }
}

static void reset_loop()
{
  char buf[64];
  snprintf(buf, sizeof(buf), "/dev/loop%llu", procid);
  int loopfd = open(buf, O_RDWR);
  if (loopfd != -1) {
    ioctl(loopfd, LOOP_CLR_FD, 0);
    close(loopfd);
  }
}

static void setup_test()
{
  prctl(PR_SET_PDEATHSIG, SIGKILL, 0, 0, 0);
  setpgrp();
  write_file("/proc/self/oom_score_adj", "1000");
}

static void execute_one(void);

#define WAIT_FLAGS __WALL

static void loop(void)
{
  int iter = 0;
  for (;; iter++) {
    reset_loop();
    int pid = fork();
    if (pid < 0)
      exit(1);
    if (pid == 0) {
      setup_test();
      execute_one();
      exit(0);
    }
    int status = 0;
    uint64_t start = current_time_ms();
    for (;;) {
      if (waitpid(-1, &status, WNOHANG | WAIT_FLAGS) == pid)
        break;
      sleep_ms(1);
      if (current_time_ms() - start < 5000)
        continue;
      kill_and_wait(pid, &status);
      break;
    }
  }
}

void execute_one(void)
{
  memcpy((void*)0x200004c0, "ext4\000", 5);
  memcpy((void*)0x200000c0, "./file0\000", 8);
  *(uint64_t*)0x20000040 = 0;
  *(uint64_t*)0x20000048 = 0;
  *(uint8_t*)0x20000050 = 0;
  *(uint64_t*)0x20000051 = -1;
  *(uint16_t*)0x20000059 = -1;
  *(uint32_t*)0x2000005b = -1;
  memcpy(
      (void*)0x20000a00,
      "\x78\x9c\xec\xdd\xcf\x6f\x1b\x59\x1d\x00\xf0\xef\x4c\xe2\x6c\x9a\x66\x49"
      "\x56\x20\xb1\xc0\x81\xd5\x6e\x21\x8b\x50\x9c\x1f\x6d\x56\x5d\x38\xb0\x88"
      "\x03\x07\x54\x69\x45\xff\x80\x2a\x24\x4e\x14\xc5\x89\xa3\xd8\x29\x4d\x94"
      "\x43\x2a\x24\x38\x70\xe0\x52\xa9\x48\x9c\xb8\x73\x43\xa8\xd7\xfe\x03\x95"
      "\xe0\x04\x55\x0f\xdc\x90\x40\x2a\xd0\x86\x43\x11\xa0\x41\xe3\x4c\xda\x34"
      "\x75\x7e\x54\x4d\x6c\xb0\x3f\x1f\xe9\x75\xe6\xcd\x78\xfc\xfd\x3e\xd7\x7e"
      "\x99\x37\xcf\xf2\x04\xd0\xb3\xde\x8b\x88\x4f\x22\xa2\x2f\x22\xbe\x16\x11"
      "\x23\xc5\xf6\xb4\x28\xb1\xb3\x57\xf2\xc7\x3d\x7d\xb2\x3d\xb7\xfb\x64\x7b"
      "\x2e\x89\x2c\xbb\xfe\xb7\xa4\x79\x4c\xbe\x6d\xff\xb9\x92\x62\x79\xb1\x38"
      "\x6c\x30\x22\xbe\xff\xdd\x88\x1f\x24\xaf\xc6\xad\x6f\x6e\x2d\xcf\x56\xab"
      "\x95\xf5\xa2\x3e\xd1\x58\x59\x9b\xa8\x6f\x6e\x8d\x2f\xad\xcc\x2e\x56\x16"
      "\x2b\xab\x97\xaf\x7c\x34\x73\xf5\xe3\xe9\xc9\xa9\x99\xb3\x69\xe8\x60\xc4"
      "\xc6\xfb\xbf\xb9\xf7\xe0\xce\xb5\x9f\xfc\xea\x3b\xe3\x93\xbf\xfb\xf1\x3f"
      "\x1f\xe4\x69\x5d\x2a\x76\x1f\x6c\xc7\x59\xda\x6b\x7a\xa9\xf9\x5a\xec\xb9"
      "\x1d\xfd\x11\xb1\x7e\x1e\xc1\x3a\xa0\xaf\x58\x96\x3a\x9c\x07\x00\x00\xa7"
      "\x93\x16\xe7\xa8\xef\x37\xcf\xff\x47\xa2\xaf\x79\x76\x0a\x00\x00\x00\x74"
      "\x93\xec\x5b\xc3\xf1\xef\x24\x22\x03\x00\x00\x00\xba\x56\x1a\x11\xc3\x91"
      "\xa4\xe5\xe2\xbb\x00\xc3\x91\xa6\xe5\x72\xc4\x40\x44\x7c\x2e\x86\xd2\x6a"
      "\xad\xde\xf8\xfa\x42\x6d\x63\x75\x3e\xdf\x17\x31\x1a\xa5\x74\x61\xa9\x5a"
      "\x99\x2c\xbe\x2b\x3c\x1a\xa5\x24\xaf\x4f\x35\xd7\x5f\xd4\xa7\x0f\xd5\x2f"
      "\x47\xc4\x3b\x11\x71\x67\xe4\x42\xb3\x5e\x9e\xab\x55\xe7\x3b\x7d\xf1\x03"
      "\x00\x00\x00\x7a\xc4\xc5\x43\xe3\xff\x7f\x8c\xec\x8d\xff\x01\x00\x00\x80"
      "\x2e\x33\xda\xe9\x04\x00\x00\x00\x80\x73\x67\xfc\x0f\x00\x00\x00\xdd\xcf"
      "\xf8\x1f\x00\x00\x00\xba\xda\xa7\xd7\xae\xe5\x25\xdb\x2d\xee\x7f\x3d\x7f"
      "\x73\x73\x63\xb9\x76\x73\x7c\xbe\x52\x5f\x2e\xaf\x6c\xcc\x95\xe7\x6a\xeb"
      "\x6b\xe5\xc5\x5a\x6d\xb1\xf9\x9b\x7d\x2b\x27\x3d\x5f\xb5\x56\x5b\xbb\x12"
      "\xab\x1b\xb7\x26\x1a\x95\x7a\x63\xa2\xbe\xb9\x75\x63\xa5\xb6\xb1\xda\xb8"
      "\xd1\xbc\xaf\xf7\x8d\x8a\xfb\x44\x03\x00\x00\x40\xfb\xbd\xf3\xe5\xfb\x0f"
      "\xff\x18\x11\x3b\xdf\xb8\xd0\x2c\xb9\x81\x62\x9f\xb1\x3a\x74\xb7\xf4\xb5"
      "\x8f\x48\xce\x25\x0f\xa0\xfd\xfa\x3a\x9d\x00\xd0\x31\xfd\x9d\x4e\x00\xe8"
      "\x18\x63\x7c\xe0\xa4\x51\xfd\xe0\x51\x3b\x7e\x7b\xf6\xb9\x00\x00\x00\xe7"
      "\x63\xec\x0b\xf7\x1f\x26\xe6\xff\xa1\x27\xbd\xfe\xfc\x3f\xd0\x2d\xcc\xff"
      "\x43\xef\x3a\x79\xfe\xff\xce\x40\x5b\x12\x01\xda\xae\x64\x94\x0f\x3d\xcf"
      "\xfc\x3f\x00\x00\x74\xbf\xe1\x66\x49\xd2\x72\x73\x2e\x30\xfb\x57\x96\xa5"
      "\x69\xb9\x1c\xf1\x76\xf3\xb6\x00\xa5\x64\x61\xa9\x5a\x99\x8c\x88\xcf\x44"
      "\xc4\x1f\x46\x4a\x6f\xe5\xf5\xa9\x4e\x27\x0d\x00\x00\x00\x00\x00\x00\x00"
      "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xff\x67\xb2\x2c\x89\x0c"
      "\x00\x00\x00\xe8\x6a\x11\xe9\x5f\x92\xe2\xfe\x5f\x63\x23\x97\x86\x0f\x5f"
      "\x1f\x18\x48\x9e\x8d\x34\x97\x11\xf1\xc3\x5f\x5c\xbf\x7b\x6b\xb6\xd1\x58"
      "\x9f\xca\xb7\xff\xfd\xf9\xf6\xc6\xcf\x8b\xed\xd3\x9d\xb8\x82\x01\x00\x00"
      "\x00\x1c\xb6\x3f\x4e\xdf\x1f\xc7\x03\x00\x00\x00\x00\x00\x00\x00\x00\x00"
      "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
      "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
      "\x00\x00\x00\x00\x00\x00\x00\x00\x00\xc0\x59\x7a\xfa\x64\x7b\x6e\xbf\xb4"
      "\x33\xee\xe3\x6f\x47\xc4\xe8\x5e\xfc\xdd\xa2\xec\xed\xe9\x8f\xc1\xe6\x72"
      "\x30\x4a\x11\x31\xb4\x9b\x44\xff\x81\xe3\x92\x88\xe8\x3b\x83\xf8\x3b\xb7"
      "\x23\xe2\xdd\x56\xed\x4f\xf2\xb4\x62\xb4\xc8\xe2\x70\xfc\x34\x22\x2e\xb4"
      "\x37\xfe\xc0\xe1\xf8\x17\xcf\x20\x3e\xf4\xb2\xfb\x79\xff\xf3\x49\xab\xcf"
      "\x5f\x1a\xef\x35\x97\xad\x3f\xff\xfd\x45\x79\x53\xfb\xfd\xdf\xee\x2b\xfd"
      "\x5f\xfa\xbc\xff\xeb\x3b\xa2\xff\x7b\xfb\x94\x31\x7e\xff\xeb\xbf\x5e\x3d"
      "\x32\xfe\xed\x88\x2f\xf6\xb7\x8a\x9f\x3c\x8f\x9f\xc7\x1a\x9a\x1a\x7c\xe9"
      "\xb8\x7c\xdb\x07\xa7\x8c\xff\xa5\xa9\x9f\x3d\x3a\x6a\x5f\xf6\xcb\x88\xb1"
      "\x4f\x23\xa2\x45\xfc\x83\xb1\x26\x1a\x2b\x6b\x13\xf5\xcd\xad\xf1\xa5\x95"
      "\xd9\xc5\xca\x62\x65\xf5\xf2\x95\x8f\x66\xae\x7e\x3c\x3d\x39\x35\x33\xb1"
      "\xb0\x54\xad\x4c\xee\xfd\xdb\x32\xc6\xf7\xbe\xf9\xa3\xd5\xe3\xda\x3f\x14"
      "\xad\xdb\x3f\x7a\xb0\xfd\x2d\x5e\xff\x4b\x2f\xd5\x8e\xf6\xf8\xf3\xff\xf9"
      "\xf3\x67\x8f\x89\xff\xe1\x07\xad\xff\xff\xdf\x3d\x26\x7e\xfe\x9e\xf8\x4a"
      "\x11\x39\xff\x5b\xf0\xd5\x62\x99\x44\xbc\x35\x76\x28\xc6\xf6\x4f\xef\x1e"
      "\xf9\x56\xc9\xe3\xcf\x1f\xd1\xfe\xc1\x13\xda\xff\xe1\xb1\xad\x7e\xe1\xd1"
      "\xbd\x3f\x3d\x3b\xe5\x43\x01\x80\x36\xa8\x6f\x6e\x2d\xcf\x56\xab\x95\xf5"
      "\xde\x5a\x89\x9d\x88\xff\x81\x34\xac\x58\x39\x9f\x95\x2c\xcb\xb2\x37\x7b"
      "\x9e\x4e\xf7\x4c\x00\x00\xc0\x59\x7b\x71\xd2\xdf\xe9\x4c\x00\x00\x00\x00"
      "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xa0\x77\xb5\xe3\xd7\xc8\x3a"
      "\xdd\x46\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
      "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
      "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
      "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
      "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
      "\x00\x00\x00\x00\x00\x00\x80\xd3\xf8\x6f\x00\x00\x00\xff\xff\xe3\x76\xdb"
      "\x44",
      1243);
  syz_mount_image(
      /*fs=*/0x200004c0, /*dir=*/0x200000c0,
      /*flags=MS_I_VERSION|MS_POSIXACL|MS_RDONLY|MS_NOSUID|MS_DIRSYNC*/
      0x810083, /*opts=*/0x20000040, /*chdir=*/9, /*size=*/0x4db,
      /*img=*/0x20000a00);
}
int main(void)
{
  syscall(__NR_mmap, /*addr=*/0x1ffff000ul, /*len=*/0x1000ul, /*prot=*/0ul,
          /*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/ 0x32ul, /*fd=*/-1,
          /*offset=*/0ul);
  syscall(__NR_mmap, /*addr=*/0x20000000ul, /*len=*/0x1000000ul,
          /*prot=PROT_WRITE|PROT_READ|PROT_EXEC*/ 7ul,
          /*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/ 0x32ul, /*fd=*/-1,
          /*offset=*/0ul);
  syscall(__NR_mmap, /*addr=*/0x21000000ul, /*len=*/0x1000ul, /*prot=*/0ul,
          /*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/ 0x32ul, /*fd=*/-1,
          /*offset=*/0ul);
  loop();
  return 0;
}
