// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE

#include <dirent.h>
#include <endian.h>
#include <errno.h>
#include <fcntl.h>
#include <sched.h>
#include <setjmp.h>
#include <signal.h>
#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <sys/prctl.h>
#include <sys/stat.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <time.h>
#include <unistd.h>

#ifndef __NR_bpf
#define __NR_bpf 321
#endif
#ifndef __NR_io_uring_setup
#define __NR_io_uring_setup 425
#endif

static __thread int clone_ongoing;
static __thread int skip_segv;
static __thread jmp_buf segv_env;

static void segv_handler(int sig, siginfo_t* info, void* ctx)
{
  if (__atomic_load_n(&clone_ongoing, __ATOMIC_RELAXED) != 0) {
    exit(sig);
  }
  uintptr_t addr = (uintptr_t)info->si_addr;
  const uintptr_t prog_start = 1 << 20;
  const uintptr_t prog_end = 100 << 20;
  int skip = __atomic_load_n(&skip_segv, __ATOMIC_RELAXED) != 0;
  int valid = addr < prog_start || addr > prog_end;
  if (skip && valid) {
    _longjmp(segv_env, 1);
  }
  exit(sig);
}

static void install_segv_handler(void)
{
  struct sigaction sa;
  memset(&sa, 0, sizeof(sa));
  sa.sa_handler = SIG_IGN;
  syscall(SYS_rt_sigaction, 0x20, &sa, NULL, 8);
  syscall(SYS_rt_sigaction, 0x21, &sa, NULL, 8);
  memset(&sa, 0, sizeof(sa));
  sa.sa_sigaction = segv_handler;
  sa.sa_flags = SA_NODEFER | SA_SIGINFO;
  sigaction(SIGSEGV, &sa, NULL);
  sigaction(SIGBUS, &sa, NULL);
}

#define NONFAILING(...)                                                        \
  ({                                                                           \
    int ok = 1;                                                                \
    __atomic_fetch_add(&skip_segv, 1, __ATOMIC_SEQ_CST);                       \
    if (_setjmp(segv_env) == 0) {                                              \
      __VA_ARGS__;                                                             \
    } else                                                                     \
      ok = 0;                                                                  \
    __atomic_fetch_sub(&skip_segv, 1, __ATOMIC_SEQ_CST);                       \
    ok;                                                                        \
  })

static void sleep_ms(uint64_t ms)
{
  usleep(ms * 1000);
}

static uint64_t current_time_ms(void)
{
  struct timespec ts;
  if (clock_gettime(CLOCK_MONOTONIC, &ts))
    exit(1);
  return (uint64_t)ts.tv_sec * 1000 + (uint64_t)ts.tv_nsec / 1000000;
}

#define BITMASK(bf_off, bf_len) (((1ull << (bf_len)) - 1) << (bf_off))
#define STORE_BY_BITMASK(type, htobe, addr, val, bf_off, bf_len)               \
  *(type*)(addr) =                                                             \
      htobe((htobe(*(type*)(addr)) & ~BITMASK((bf_off), (bf_len))) |           \
            (((type)(val) << (bf_off)) & BITMASK((bf_off), (bf_len))))

static bool write_file(const char* file, const char* what, ...)
{
  char buf[1024];
  va_list args;
  va_start(args, what);
  vsnprintf(buf, sizeof(buf), what, args);
  va_end(args);
  buf[sizeof(buf) - 1] = 0;
  int len = strlen(buf);
  int fd = open(file, O_WRONLY | O_CLOEXEC);
  if (fd == -1)
    return false;
  if (write(fd, buf, len) != len) {
    int err = errno;
    close(fd);
    errno = err;
    return false;
  }
  close(fd);
  return true;
}

#define SIZEOF_IO_URING_SQE 64
#define SIZEOF_IO_URING_CQE 16
#define SQ_HEAD_OFFSET 0
#define SQ_TAIL_OFFSET 64
#define SQ_RING_MASK_OFFSET 256
#define SQ_RING_ENTRIES_OFFSET 264
#define SQ_FLAGS_OFFSET 276
#define SQ_DROPPED_OFFSET 272
#define CQ_HEAD_OFFSET 128
#define CQ_TAIL_OFFSET 192
#define CQ_RING_MASK_OFFSET 260
#define CQ_RING_ENTRIES_OFFSET 268
#define CQ_RING_OVERFLOW_OFFSET 284
#define CQ_FLAGS_OFFSET 280
#define CQ_CQES_OFFSET 320

struct io_sqring_offsets {
  uint32_t head;
  uint32_t tail;
  uint32_t ring_mask;
  uint32_t ring_entries;
  uint32_t flags;
  uint32_t dropped;
  uint32_t array;
  uint32_t resv1;
  uint64_t resv2;
};

struct io_cqring_offsets {
  uint32_t head;
  uint32_t tail;
  uint32_t ring_mask;
  uint32_t ring_entries;
  uint32_t overflow;
  uint32_t cqes;
  uint64_t resv[2];
};

struct io_uring_params {
  uint32_t sq_entries;
  uint32_t cq_entries;
  uint32_t flags;
  uint32_t sq_thread_cpu;
  uint32_t sq_thread_idle;
  uint32_t features;
  uint32_t resv[4];
  struct io_sqring_offsets sq_off;
  struct io_cqring_offsets cq_off;
};

#define IORING_OFF_SQ_RING 0
#define IORING_OFF_SQES 0x10000000ULL

static long syz_io_uring_setup(volatile long a0, volatile long a1,
                               volatile long a2, volatile long a3,
                               volatile long a4, volatile long a5)
{
  uint32_t entries = (uint32_t)a0;
  struct io_uring_params* setup_params = (struct io_uring_params*)a1;
  void* vma1 = (void*)a2;
  void* vma2 = (void*)a3;
  void** ring_ptr_out = (void**)a4;
  void** sqes_ptr_out = (void**)a5;
  uint32_t fd_io_uring = syscall(__NR_io_uring_setup, entries, setup_params);
  uint32_t sq_ring_sz =
      setup_params->sq_off.array + setup_params->sq_entries * sizeof(uint32_t);
  uint32_t cq_ring_sz = setup_params->cq_off.cqes +
                        setup_params->cq_entries * SIZEOF_IO_URING_CQE;
  uint32_t ring_sz = sq_ring_sz > cq_ring_sz ? sq_ring_sz : cq_ring_sz;
  *ring_ptr_out = mmap(vma1, ring_sz, PROT_READ | PROT_WRITE,
                       MAP_SHARED | MAP_POPULATE | MAP_FIXED, fd_io_uring,
                       IORING_OFF_SQ_RING);
  uint32_t sqes_sz = setup_params->sq_entries * SIZEOF_IO_URING_SQE;
  *sqes_ptr_out =
      mmap(vma2, sqes_sz, PROT_READ | PROT_WRITE,
           MAP_SHARED | MAP_POPULATE | MAP_FIXED, fd_io_uring, IORING_OFF_SQES);
  return fd_io_uring;
}

static void kill_and_wait(int pid, int* status)
{
  kill(-pid, SIGKILL);
  kill(pid, SIGKILL);
  for (int i = 0; i < 100; i++) {
    if (waitpid(-1, status, WNOHANG | __WALL) == pid)
      return;
    usleep(1000);
  }
  DIR* dir = opendir("/sys/fs/fuse/connections");
  if (dir) {
    for (;;) {
      struct dirent* ent = readdir(dir);
      if (!ent)
        break;
      if (strcmp(ent->d_name, ".") == 0 || strcmp(ent->d_name, "..") == 0)
        continue;
      char abort[300];
      snprintf(abort, sizeof(abort), "/sys/fs/fuse/connections/%s/abort",
               ent->d_name);
      int fd = open(abort, O_WRONLY);
      if (fd == -1) {
        continue;
      }
      if (write(fd, abort, 1) < 0) {
      }
      close(fd);
    }
    closedir(dir);
  } else {
  }
  while (waitpid(-1, status, __WALL) != pid) {
  }
}

static void setup_test()
{
  prctl(PR_SET_PDEATHSIG, SIGKILL, 0, 0, 0);
  setpgrp();
  write_file("/proc/self/oom_score_adj", "1000");
}

#define USLEEP_FORKED_CHILD (3 * 50 * 1000)

static long handle_clone_ret(long ret)
{
  if (ret != 0) {
    __atomic_store_n(&clone_ongoing, 0, __ATOMIC_RELAXED);
    return ret;
  }
  usleep(USLEEP_FORKED_CHILD);
  syscall(__NR_exit, 0);
  while (1) {
  }
}

static long syz_clone(volatile long flags, volatile long stack,
                      volatile long stack_len, volatile long ptid,
                      volatile long ctid, volatile long tls)
{
  long sp = (stack + stack_len) & ~15;
  __atomic_store_n(&clone_ongoing, 1, __ATOMIC_RELAXED);
  long ret = (long)syscall(__NR_clone, flags & ~CLONE_VM, sp, ptid, ctid, tls);
  return handle_clone_ret(ret);
}

static void execute_one(void);

#define WAIT_FLAGS __WALL

static void loop(void)
{
  int iter = 0;
  for (;; iter++) {
    int pid = fork();
    if (pid < 0)
      exit(1);
    if (pid == 0) {
      setup_test();
      execute_one();
      exit(0);
    }
    int status = 0;
    uint64_t start = current_time_ms();
    for (;;) {
      if (waitpid(-1, &status, WNOHANG | WAIT_FLAGS) == pid)
        break;
      sleep_ms(1);
      if (current_time_ms() - start < 5000)
        continue;
      kill_and_wait(pid, &status);
      break;
    }
  }
}

uint64_t r[2] = {0xffffffffffffffff, 0xffffffffffffffff};

void execute_one(void)
{
  intptr_t res = 0;
  syscall(__NR_perf_event_open, 0ul, 0, -1ul, -1, 0ul);
  syscall(__NR_bpf, 0x1aul, 0ul, 0ul);
  syscall(__NR_mmap, 0x20400000ul, 0xc00000ul, 2ul, 0x2e031ul, -1,
          0x10000000ul);
  syscall(__NR_creat, 0ul, 0ul);
  NONFAILING(syz_io_uring_setup(0x27af, 0, 0x200a0000, 0x20ffc000, 0, 0));
  res = syscall(__NR_socket, 2ul, 3ul, 1);
  if (res != -1)
    r[0] = res;
  syscall(__NR_ioctl, r[0], 0x8903, 0ul);
  NONFAILING(*(uint32_t*)0x200000c0 = 0);
  NONFAILING(*(uint32_t*)0x200000c4 = 0x80);
  NONFAILING(*(uint8_t*)0x200000c8 = 0);
  NONFAILING(*(uint8_t*)0x200000c9 = 0);
  NONFAILING(*(uint8_t*)0x200000ca = 0);
  NONFAILING(*(uint8_t*)0x200000cb = 0);
  NONFAILING(*(uint32_t*)0x200000cc = 0);
  NONFAILING(*(uint64_t*)0x200000d0 = 0x71c);
  NONFAILING(*(uint64_t*)0x200000d8 = 0);
  NONFAILING(*(uint64_t*)0x200000e0 = 0);
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200000e8, 0, 0, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200000e8, 1, 1, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200000e8, 0, 2, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200000e8, 0, 3, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200000e8, 0, 4, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200000e8, 0, 5, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200000e8, 0, 6, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200000e8, 0, 7, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200000e8, 0, 8, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200000e8, 0, 9, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200000e8, 0, 10, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200000e8, 0, 11, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200000e8, 0, 12, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200000e8, 0, 13, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200000e8, 0, 14, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200000e8, 0, 15, 2));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200000e8, 0, 17, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200000e8, 0, 18, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200000e8, 0, 19, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200000e8, 0, 20, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200000e8, 0, 21, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200000e8, 0, 22, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200000e8, 0, 23, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200000e8, 0, 24, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200000e8, 0, 25, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200000e8, 0, 26, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200000e8, 0, 27, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200000e8, 0, 28, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200000e8, 0, 29, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200000e8, 0, 30, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200000e8, 0, 31, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200000e8, 0, 32, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200000e8, 0, 33, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200000e8, 0, 34, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200000e8, 0, 35, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200000e8, 1, 36, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200000e8, 1, 37, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200000e8, 0, 38, 26));
  NONFAILING(*(uint32_t*)0x200000f0 = 0x2a);
  NONFAILING(*(uint32_t*)0x200000f4 = 0);
  NONFAILING(*(uint64_t*)0x200000f8 = 0);
  NONFAILING(*(uint64_t*)0x20000100 = 0);
  NONFAILING(*(uint64_t*)0x20000108 = 0);
  NONFAILING(*(uint64_t*)0x20000110 = 0);
  NONFAILING(*(uint32_t*)0x20000118 = 0);
  NONFAILING(*(uint32_t*)0x2000011c = 0);
  NONFAILING(*(uint64_t*)0x20000120 = 0);
  NONFAILING(*(uint32_t*)0x20000128 = 0);
  NONFAILING(*(uint16_t*)0x2000012c = 0);
  NONFAILING(*(uint16_t*)0x2000012e = 0);
  NONFAILING(*(uint32_t*)0x20000130 = 0);
  NONFAILING(*(uint32_t*)0x20000134 = 0);
  NONFAILING(*(uint64_t*)0x20000138 = 0);
  syscall(__NR_perf_event_open, 0x200000c0ul, 0, 0ul, -1, 0ul);
  NONFAILING(syz_clone(0, 0, 0xfffffffffffffeef, 0, 0, 0));
  syscall(__NR_recvfrom, -1, 0ul, 0ul, 0x40012020ul, 0ul, 0ul);
  syscall(__NR_setsockopt, -1, 0, 0xa, 0ul, 0ul);
  syscall(__NR_sendmsg, -1, 0ul, 0ul);
  syscall(__NR_ioctl, -1, 0x8916, 0ul);
  res = syscall(__NR_openat, 0xffffffffffffff9cul, 0ul, 0x101000ul, 0ul);
  if (res != -1)
    r[1] = res;
  syscall(__NR_fchown, r[1], 0xee01, 0);
  syscall(__NR_sendmsg, -1, 0ul, 0x1050ul);
  syscall(__NR_read, -1, 0ul, 0ul);
}
int main(void)
{
  syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
  syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
  syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
  install_segv_handler();
  loop();
  return 0;
}
