// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE

#include <endian.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

uint64_t r[5] = {0xffffffffffffffff, 0xffffffffffffffff, 0x0,
                 0xffffffffffffffff, 0xffffffffffffffff};

int main(void)
{
  syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
  syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
  syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
  intptr_t res = 0;
  memcpy((void*)0x20000040, "/dev/iommu\000", 11);
  res = syscall(__NR_openat, 0xffffffffffffff9cul, 0x20000040ul, 0ul, 0ul);
  if (res != -1)
    r[0] = res;
  *(uint32_t*)0x20000000 = 0xc;
  *(uint32_t*)0x20000004 = 0;
  syscall(__NR_ioctl, r[0], 0x3b81, 0x20000000ul);
  memcpy((void*)0x20000000, "/dev/iommu\000", 11);
  res = syscall(__NR_openat, 0xffffffffffffff9cul, 0x20000000ul, 0ul, 0ul);
  if (res != -1)
    r[1] = res;
  *(uint32_t*)0x20000140 = 0xc;
  *(uint32_t*)0x20000144 = 0;
  res = syscall(__NR_ioctl, r[1], 0x3b81, 0x20000140ul);
  if (res != -1)
    r[2] = *(uint32_t*)0x20000148;
  *(uint32_t*)0x200000c0 = 0xc;
  *(uint32_t*)0x200000c4 = r[2];
  *(uint16_t*)0x200000c8 = 1;
  *(uint16_t*)0x200000ca = 0;
  syscall(__NR_ioctl, r[0], 0x3b88, 0x200000c0ul);
  *(uint32_t*)0x20000080 = 0x20;
  *(uint32_t*)0x20000084 = 1;
  *(uint64_t*)0x20000088 = -1;
  *(uint64_t*)0x20000090 = 0;
  *(uint64_t*)0x20000098 = 0x80000001;
  syscall(__NR_ioctl, r[0], 0x3b71, 0x20000080ul);
  *(uint32_t*)0x20000100 = 0x38;
  *(uint32_t*)0x20000104 = 5;
  *(uint32_t*)0x20000108 = r[2];
  *(uint32_t*)0x2000010c = 0;
  *(uint32_t*)0x20000114 = 0;
  res = syscall(__NR_ioctl, r[0], 0x3ba0, 0x20000100ul);
  if (res != -1)
    r[3] = *(uint32_t*)0x20000110;
  memcpy((void*)0x20000000, "/dev/iommu\000", 11);
  res = syscall(__NR_openat, 0xffffffffffffff9cul, 0x20000000ul, 0ul, 0ul);
  if (res != -1)
    r[4] = res;
  *(uint32_t*)0x200001c0 = 0x38;
  *(uint32_t*)0x200001c4 = 8;
  *(uint32_t*)0x200001c8 = r[3];
  *(uint32_t*)0x200001cc = 0x3d27;
  *(uint32_t*)0x200001d0 = 7;
  *(uint32_t*)0x200001d4 = 0x11ccc9;
  *(uint64_t*)0x200001d8 = 0xf7;
  *(uint64_t*)0x200001e0 = 0x20000280;
  memcpy(
      (void*)0x20000280,
      "\x6b\x72\x71\xef\xb4\xb9\x8c\xc7\x91\xb8\xd9\x66\x05\x45\xf3\xfc\x3b\xe8"
      "\xf2\xe5\x5f\xa6\xb8\xd2\x47\x1f\x7e\xd4\xb4\x47\x8a\xb6\x0f\xb8\x32\x9b"
      "\x71\x4c\x41\x9e\xc1\x1d\xe9\x95\x98\x6c\x1f\x15\x33\x94\xd0\x86\x45\xba"
      "\x8b\x2b\xa0\x35\x16\x73\xfc\xec\x1a\x1b\xbc\xfa\x57\x56\xd2\x94\xd5\x34"
      "\xba\x29\xc4\x73\x0d\xd1\x0a\x0a\x8d\xfe\x3e\xc5\xbd\x38\x8f\x47\x2a\xe3"
      "\xb4\xd5\x2a\x75\xb6\x6c\xdd\xd9\x95\x94\xfc\x87\x48\x00\x61\x27\xf6\xb2"
      "\x0e\xed\xef\xbe\x71\x5f\x7a\xea\xf6\x5d\xcd\xf5\x6b\x9a\x7f\xb2\x92\x14"
      "\xcd\x41\xbd\x43\xc4\xe5\xd5\x57\x5c\x21\x25\x94\xac\x99\x54\x3e\x61\x91"
      "\xb2\x74\xf1\x80\x8d\x89\x0a\xc8\x99\x1b\x89\xa0\xca\xb1\xb0\x34\x9e\xeb"
      "\x8a\x62\x6b\xec\x5d\x8b\x31\x85\xef\x4e\x60\x91\x08\xf3\xd0\xde\xcc\xdd"
      "\x3b\x65\xf3\x1f\xe3\x58\xa5\x88\x57\xd4\xa3\x6b\xa1\x79\x11\x79\xc6\x98"
      "\xf9\xf3\xea\xb6\x87\xf3\x45\xfa\xb2\x1e\x03\xaa\x02\x00\x50\xf8\xa3\x88"
      "\x17\xc4\x1d\xc4\x60\x02\xcb\x7f\x67\x3d\xcd\xcb\xc2\x32\xc7\x9d\x09\x53"
      "\x76\x8b\x90\x63\x71\xd2\xf2\x7f\x2f\x26\x64\x1a\x61",
      247);
  *(uint32_t*)0x200001e8 = 0x10004;
  syscall(__NR_ioctl, r[4], 0x3ba0, 0x200001c0ul);
  return 0;
}
