// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE

#include <dirent.h>
#include <endian.h>
#include <errno.h>
#include <fcntl.h>
#include <sched.h>
#include <setjmp.h>
#include <signal.h>
#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/ioctl.h>
#include <sys/mount.h>
#include <sys/prctl.h>
#include <sys/resource.h>
#include <sys/stat.h>
#include <sys/swap.h>
#include <sys/syscall.h>
#include <sys/time.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <time.h>
#include <unistd.h>

#include <linux/capability.h>
#include <linux/falloc.h>

static unsigned long long procid;

static __thread int clone_ongoing;
static __thread int skip_segv;
static __thread jmp_buf segv_env;

static void segv_handler(int sig, siginfo_t* info, void* ctx)
{
  if (__atomic_load_n(&clone_ongoing, __ATOMIC_RELAXED) != 0) {
    exit(sig);
  }
  uintptr_t addr = (uintptr_t)info->si_addr;
  const uintptr_t prog_start = 1 << 20;
  const uintptr_t prog_end = 100 << 20;
  int skip = __atomic_load_n(&skip_segv, __ATOMIC_RELAXED) != 0;
  int valid = addr < prog_start || addr > prog_end;
  if (skip && valid) {
    _longjmp(segv_env, 1);
  }
  exit(sig);
}

static void install_segv_handler(void)
{
  struct sigaction sa;
  memset(&sa, 0, sizeof(sa));
  sa.sa_handler = SIG_IGN;
  syscall(SYS_rt_sigaction, 0x20, &sa, NULL, 8);
  syscall(SYS_rt_sigaction, 0x21, &sa, NULL, 8);
  memset(&sa, 0, sizeof(sa));
  sa.sa_sigaction = segv_handler;
  sa.sa_flags = SA_NODEFER | SA_SIGINFO;
  sigaction(SIGSEGV, &sa, NULL);
  sigaction(SIGBUS, &sa, NULL);
}

#define NONFAILING(...)                                                        \
  ({                                                                           \
    int ok = 1;                                                                \
    __atomic_fetch_add(&skip_segv, 1, __ATOMIC_SEQ_CST);                       \
    if (_setjmp(segv_env) == 0) {                                              \
      __VA_ARGS__;                                                             \
    } else                                                                     \
      ok = 0;                                                                  \
    __atomic_fetch_sub(&skip_segv, 1, __ATOMIC_SEQ_CST);                       \
    ok;                                                                        \
  })

static void sleep_ms(uint64_t ms)
{
  usleep(ms * 1000);
}

static uint64_t current_time_ms(void)
{
  struct timespec ts;
  if (clock_gettime(CLOCK_MONOTONIC, &ts))
    exit(1);
  return (uint64_t)ts.tv_sec * 1000 + (uint64_t)ts.tv_nsec / 1000000;
}

static void use_temporary_dir(void)
{
  char tmpdir_template[] = "./syzkaller.XXXXXX";
  char* tmpdir = mkdtemp(tmpdir_template);
  if (!tmpdir)
    exit(1);
  if (chmod(tmpdir, 0777))
    exit(1);
  if (chdir(tmpdir))
    exit(1);
}

#define BITMASK(bf_off, bf_len) (((1ull << (bf_len)) - 1) << (bf_off))
#define STORE_BY_BITMASK(type, htobe, addr, val, bf_off, bf_len)               \
  *(type*)(addr) =                                                             \
      htobe((htobe(*(type*)(addr)) & ~BITMASK((bf_off), (bf_len))) |           \
            (((type)(val) << (bf_off)) & BITMASK((bf_off), (bf_len))))

static bool write_file(const char* file, const char* what, ...)
{
  char buf[1024];
  va_list args;
  va_start(args, what);
  vsnprintf(buf, sizeof(buf), what, args);
  va_end(args);
  buf[sizeof(buf) - 1] = 0;
  int len = strlen(buf);
  int fd = open(file, O_WRONLY | O_CLOEXEC);
  if (fd == -1)
    return false;
  if (write(fd, buf, len) != len) {
    int err = errno;
    close(fd);
    errno = err;
    return false;
  }
  close(fd);
  return true;
}

static int runcmdline(char* cmdline)
{
  int ret = system(cmdline);
  if (ret) {
  }
  return ret;
}

#define MAX_FDS 30

static void mount_cgroups(const char* dir, const char** controllers, int count)
{
  if (mkdir(dir, 0777)) {
    return;
  }
  char enabled[128] = {0};
  int i = 0;
  for (; i < count; i++) {
    if (mount("none", dir, "cgroup", 0, controllers[i])) {
      continue;
    }
    umount(dir);
    strcat(enabled, ",");
    strcat(enabled, controllers[i]);
  }
  if (enabled[0] == 0) {
    if (rmdir(dir) && errno != EBUSY)
      exit(1);
    return;
  }
  if (mount("none", dir, "cgroup", 0, enabled + 1)) {
    if (rmdir(dir) && errno != EBUSY)
      exit(1);
  }
  if (chmod(dir, 0777)) {
  }
}

static void mount_cgroups2(const char** controllers, int count)
{
  if (mkdir("/syzcgroup/unified", 0777)) {
    return;
  }
  if (mount("none", "/syzcgroup/unified", "cgroup2", 0, NULL)) {
    if (rmdir("/syzcgroup/unified") && errno != EBUSY)
      exit(1);
    return;
  }
  if (chmod("/syzcgroup/unified", 0777)) {
  }
  int control = open("/syzcgroup/unified/cgroup.subtree_control", O_WRONLY);
  if (control == -1)
    return;
  int i;
  for (i = 0; i < count; i++)
    if (write(control, controllers[i], strlen(controllers[i])) < 0) {
    }
  close(control);
}

static void setup_cgroups()
{
  const char* unified_controllers[] = {"+cpu", "+io", "+pids"};
  const char* net_controllers[] = {"net", "net_prio", "devices", "blkio",
                                   "freezer"};
  const char* cpu_controllers[] = {"cpuset", "cpuacct", "hugetlb", "rlimit",
                                   "memory"};
  if (mkdir("/syzcgroup", 0777)) {
    return;
  }
  mount_cgroups2(unified_controllers,
                 sizeof(unified_controllers) / sizeof(unified_controllers[0]));
  mount_cgroups("/syzcgroup/net", net_controllers,
                sizeof(net_controllers) / sizeof(net_controllers[0]));
  mount_cgroups("/syzcgroup/cpu", cpu_controllers,
                sizeof(cpu_controllers) / sizeof(cpu_controllers[0]));
  write_file("/syzcgroup/cpu/cgroup.clone_children", "1");
  write_file("/syzcgroup/cpu/cpuset.memory_pressure_enabled", "1");
}

static void setup_cgroups_loop()
{
  int pid = getpid();
  char file[128];
  char cgroupdir[64];
  snprintf(cgroupdir, sizeof(cgroupdir), "/syzcgroup/unified/syz%llu", procid);
  if (mkdir(cgroupdir, 0777)) {
  }
  snprintf(file, sizeof(file), "%s/pids.max", cgroupdir);
  write_file(file, "32");
  snprintf(file, sizeof(file), "%s/cgroup.procs", cgroupdir);
  write_file(file, "%d", pid);
  snprintf(cgroupdir, sizeof(cgroupdir), "/syzcgroup/cpu/syz%llu", procid);
  if (mkdir(cgroupdir, 0777)) {
  }
  snprintf(file, sizeof(file), "%s/cgroup.procs", cgroupdir);
  write_file(file, "%d", pid);
  snprintf(file, sizeof(file), "%s/memory.soft_limit_in_bytes", cgroupdir);
  write_file(file, "%d", 299 << 20);
  snprintf(file, sizeof(file), "%s/memory.limit_in_bytes", cgroupdir);
  write_file(file, "%d", 300 << 20);
  snprintf(cgroupdir, sizeof(cgroupdir), "/syzcgroup/net/syz%llu", procid);
  if (mkdir(cgroupdir, 0777)) {
  }
  snprintf(file, sizeof(file), "%s/cgroup.procs", cgroupdir);
  write_file(file, "%d", pid);
}

static void setup_cgroups_test()
{
  char cgroupdir[64];
  snprintf(cgroupdir, sizeof(cgroupdir), "/syzcgroup/unified/syz%llu", procid);
  if (symlink(cgroupdir, "./cgroup")) {
  }
  snprintf(cgroupdir, sizeof(cgroupdir), "/syzcgroup/cpu/syz%llu", procid);
  if (symlink(cgroupdir, "./cgroup.cpu")) {
  }
  snprintf(cgroupdir, sizeof(cgroupdir), "/syzcgroup/net/syz%llu", procid);
  if (symlink(cgroupdir, "./cgroup.net")) {
  }
}

static void setup_common()
{
  if (mount(0, "/sys/fs/fuse/connections", "fusectl", 0, 0)) {
  }
}

static void setup_binderfs()
{
  if (mkdir("/dev/binderfs", 0777)) {
  }
  if (mount("binder", "/dev/binderfs", "binder", 0, NULL)) {
  }
}

static void loop();

static void sandbox_common()
{
  prctl(PR_SET_PDEATHSIG, SIGKILL, 0, 0, 0);
  setsid();
  struct rlimit rlim;
  rlim.rlim_cur = rlim.rlim_max = (200 << 20);
  setrlimit(RLIMIT_AS, &rlim);
  rlim.rlim_cur = rlim.rlim_max = 32 << 20;
  setrlimit(RLIMIT_MEMLOCK, &rlim);
  rlim.rlim_cur = rlim.rlim_max = 136 << 20;
  setrlimit(RLIMIT_FSIZE, &rlim);
  rlim.rlim_cur = rlim.rlim_max = 1 << 20;
  setrlimit(RLIMIT_STACK, &rlim);
  rlim.rlim_cur = rlim.rlim_max = 128 << 20;
  setrlimit(RLIMIT_CORE, &rlim);
  rlim.rlim_cur = rlim.rlim_max = 256;
  setrlimit(RLIMIT_NOFILE, &rlim);
  if (unshare(CLONE_NEWNS)) {
  }
  if (mount(NULL, "/", NULL, MS_REC | MS_PRIVATE, NULL)) {
  }
  if (unshare(CLONE_NEWIPC)) {
  }
  if (unshare(0x02000000)) {
  }
  if (unshare(CLONE_NEWUTS)) {
  }
  if (unshare(CLONE_SYSVSEM)) {
  }
  typedef struct {
    const char* name;
    const char* value;
  } sysctl_t;
  static const sysctl_t sysctls[] = {
      {"/proc/sys/kernel/shmmax", "16777216"},
      {"/proc/sys/kernel/shmall", "536870912"},
      {"/proc/sys/kernel/shmmni", "1024"},
      {"/proc/sys/kernel/msgmax", "8192"},
      {"/proc/sys/kernel/msgmni", "1024"},
      {"/proc/sys/kernel/msgmnb", "1024"},
      {"/proc/sys/kernel/sem", "1024 1048576 500 1024"},
  };
  unsigned i;
  for (i = 0; i < sizeof(sysctls) / sizeof(sysctls[0]); i++)
    write_file(sysctls[i].name, sysctls[i].value);
}

static int wait_for_loop(int pid)
{
  if (pid < 0)
    exit(1);
  int status = 0;
  while (waitpid(-1, &status, __WALL) != pid) {
  }
  return WEXITSTATUS(status);
}

static void drop_caps(void)
{
  struct __user_cap_header_struct cap_hdr = {};
  struct __user_cap_data_struct cap_data[2] = {};
  cap_hdr.version = _LINUX_CAPABILITY_VERSION_3;
  cap_hdr.pid = getpid();
  if (syscall(SYS_capget, &cap_hdr, &cap_data))
    exit(1);
  const int drop = (1 << CAP_SYS_PTRACE) | (1 << CAP_SYS_NICE);
  cap_data[0].effective &= ~drop;
  cap_data[0].permitted &= ~drop;
  cap_data[0].inheritable &= ~drop;
  if (syscall(SYS_capset, &cap_hdr, &cap_data))
    exit(1);
}

static int do_sandbox_none(void)
{
  if (unshare(CLONE_NEWPID)) {
  }
  int pid = fork();
  if (pid != 0)
    return wait_for_loop(pid);
  setup_common();
  sandbox_common();
  drop_caps();
  if (unshare(CLONE_NEWNET)) {
  }
  write_file("/proc/sys/net/ipv4/ping_group_range", "0 65535");
  setup_binderfs();
  loop();
  exit(1);
}

#define FS_IOC_SETFLAGS _IOW('f', 2, long)
static void remove_dir(const char* dir)
{
  int iter = 0;
  DIR* dp = 0;
retry:
  while (umount2(dir, MNT_DETACH | UMOUNT_NOFOLLOW) == 0) {
  }
  dp = opendir(dir);
  if (dp == NULL) {
    if (errno == EMFILE) {
      exit(1);
    }
    exit(1);
  }
  struct dirent* ep = 0;
  while ((ep = readdir(dp))) {
    if (strcmp(ep->d_name, ".") == 0 || strcmp(ep->d_name, "..") == 0)
      continue;
    char filename[FILENAME_MAX];
    snprintf(filename, sizeof(filename), "%s/%s", dir, ep->d_name);
    while (umount2(filename, MNT_DETACH | UMOUNT_NOFOLLOW) == 0) {
    }
    struct stat st;
    if (lstat(filename, &st))
      exit(1);
    if (S_ISDIR(st.st_mode)) {
      remove_dir(filename);
      continue;
    }
    int i;
    for (i = 0;; i++) {
      if (unlink(filename) == 0)
        break;
      if (errno == EPERM) {
        int fd = open(filename, O_RDONLY);
        if (fd != -1) {
          long flags = 0;
          if (ioctl(fd, FS_IOC_SETFLAGS, &flags) == 0) {
          }
          close(fd);
          continue;
        }
      }
      if (errno == EROFS) {
        break;
      }
      if (errno != EBUSY || i > 100)
        exit(1);
      if (umount2(filename, MNT_DETACH | UMOUNT_NOFOLLOW))
        exit(1);
    }
  }
  closedir(dp);
  for (int i = 0;; i++) {
    if (rmdir(dir) == 0)
      break;
    if (i < 100) {
      if (errno == EPERM) {
        int fd = open(dir, O_RDONLY);
        if (fd != -1) {
          long flags = 0;
          if (ioctl(fd, FS_IOC_SETFLAGS, &flags) == 0) {
          }
          close(fd);
          continue;
        }
      }
      if (errno == EROFS) {
        break;
      }
      if (errno == EBUSY) {
        if (umount2(dir, MNT_DETACH | UMOUNT_NOFOLLOW))
          exit(1);
        continue;
      }
      if (errno == ENOTEMPTY) {
        if (iter < 100) {
          iter++;
          goto retry;
        }
      }
    }
    exit(1);
  }
}

static void kill_and_wait(int pid, int* status)
{
  kill(-pid, SIGKILL);
  kill(pid, SIGKILL);
  for (int i = 0; i < 100; i++) {
    if (waitpid(-1, status, WNOHANG | __WALL) == pid)
      return;
    usleep(1000);
  }
  DIR* dir = opendir("/sys/fs/fuse/connections");
  if (dir) {
    for (;;) {
      struct dirent* ent = readdir(dir);
      if (!ent)
        break;
      if (strcmp(ent->d_name, ".") == 0 || strcmp(ent->d_name, "..") == 0)
        continue;
      char abort[300];
      snprintf(abort, sizeof(abort), "/sys/fs/fuse/connections/%s/abort",
               ent->d_name);
      int fd = open(abort, O_WRONLY);
      if (fd == -1) {
        continue;
      }
      if (write(fd, abort, 1) < 0) {
      }
      close(fd);
    }
    closedir(dir);
  } else {
  }
  while (waitpid(-1, status, __WALL) != pid) {
  }
}

static void setup_loop()
{
  setup_cgroups_loop();
}

static void setup_test()
{
  prctl(PR_SET_PDEATHSIG, SIGKILL, 0, 0, 0);
  setpgrp();
  setup_cgroups_test();
  write_file("/proc/self/oom_score_adj", "1000");
  if (symlink("/dev/binderfs", "./binderfs")) {
  }
}

static void close_fds()
{
  for (int fd = 3; fd < MAX_FDS; fd++)
    close(fd);
}

static void setup_sysctl()
{
  char mypid[32];
  snprintf(mypid, sizeof(mypid), "%d", getpid());
  struct {
    const char* name;
    const char* data;
  } files[] = {
      {"/sys/kernel/debug/x86/nmi_longest_ns", "10000000000"},
      {"/proc/sys/kernel/hung_task_check_interval_secs", "20"},
      {"/proc/sys/net/core/bpf_jit_kallsyms", "1"},
      {"/proc/sys/net/core/bpf_jit_harden", "0"},
      {"/proc/sys/kernel/kptr_restrict", "0"},
      {"/proc/sys/kernel/softlockup_all_cpu_backtrace", "1"},
      {"/proc/sys/fs/mount-max", "100"},
      {"/proc/sys/vm/oom_dump_tasks", "0"},
      {"/proc/sys/debug/exception-trace", "0"},
      {"/proc/sys/kernel/printk", "7 4 1 3"},
      {"/proc/sys/kernel/keys/gc_delay", "1"},
      {"/proc/sys/vm/oom_kill_allocating_task", "1"},
      {"/proc/sys/kernel/ctrl-alt-del", "0"},
      {"/proc/sys/kernel/cad_pid", mypid},
  };
  for (size_t i = 0; i < sizeof(files) / sizeof(files[0]); i++) {
    if (!write_file(files[i].name, files[i].data))
      printf("write to %s failed: %s\n", files[i].name, strerror(errno));
  }
}

#define SWAP_FILE "./swap-file"
#define SWAP_FILE_SIZE (128 * 1000 * 1000)

static void setup_swap()
{
  swapoff(SWAP_FILE);
  unlink(SWAP_FILE);
  int fd = open(SWAP_FILE, O_CREAT | O_WRONLY | O_CLOEXEC, 0600);
  if (fd == -1) {
    exit(1);
    return;
  }
  fallocate(fd, FALLOC_FL_ZERO_RANGE, 0, SWAP_FILE_SIZE);
  close(fd);
  char cmdline[64];
  sprintf(cmdline, "mkswap %s", SWAP_FILE);
  if (runcmdline(cmdline)) {
    exit(1);
    return;
  }
  if (swapon(SWAP_FILE, SWAP_FLAG_PREFER) == 1) {
    exit(1);
    return;
  }
}

static void execute_one(void);

#define WAIT_FLAGS __WALL

static void loop(void)
{
  setup_loop();
  int iter = 0;
  for (;; iter++) {
    char cwdbuf[32];
    sprintf(cwdbuf, "./%d", iter);
    if (mkdir(cwdbuf, 0777))
      exit(1);
    int pid = fork();
    if (pid < 0)
      exit(1);
    if (pid == 0) {
      if (chdir(cwdbuf))
        exit(1);
      setup_test();
      execute_one();
      close_fds();
      exit(0);
    }
    int status = 0;
    uint64_t start = current_time_ms();
    for (;;) {
      if (waitpid(-1, &status, WNOHANG | WAIT_FLAGS) == pid)
        break;
      sleep_ms(1);
      if (current_time_ms() - start < 5000)
        continue;
      kill_and_wait(pid, &status);
      break;
    }
    remove_dir(cwdbuf);
  }
}

uint64_t r[1] = {0xffffffffffffffff};

void execute_one(void)
{
  intptr_t res = 0;
  NONFAILING(*(uint32_t*)0x20001280 = 1);
  NONFAILING(*(uint32_t*)0x20001284 = 0x80);
  NONFAILING(*(uint8_t*)0x20001288 = 0);
  NONFAILING(*(uint8_t*)0x20001289 = 0);
  NONFAILING(*(uint8_t*)0x2000128a = 0);
  NONFAILING(*(uint8_t*)0x2000128b = 0);
  NONFAILING(*(uint32_t*)0x2000128c = 0);
  NONFAILING(*(uint64_t*)0x20001290 = 8);
  NONFAILING(*(uint64_t*)0x20001298 = 0xb80a2);
  NONFAILING(*(uint64_t*)0x200012a0 = 0);
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200012a8, 0, 0, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200012a8, 0, 1, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200012a8, 0, 2, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200012a8, 0, 3, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200012a8, 0, 4, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200012a8, 0, 5, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200012a8, 0, 6, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200012a8, 0, 7, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200012a8, 0, 8, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200012a8, 0, 9, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200012a8, 0, 10, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200012a8, 0, 11, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200012a8, 0, 12, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200012a8, 0, 13, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200012a8, 0, 14, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200012a8, 0, 15, 2));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200012a8, 0, 17, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200012a8, 0, 18, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200012a8, 0, 19, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200012a8, 0, 20, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200012a8, 0, 21, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200012a8, 0, 22, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200012a8, 0, 23, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200012a8, 0, 24, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200012a8, 0, 25, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200012a8, 0, 26, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200012a8, 0, 27, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200012a8, 0, 28, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200012a8, 0, 29, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200012a8, 0, 30, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200012a8, 0, 31, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200012a8, 0, 32, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200012a8, 0, 33, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200012a8, 0, 34, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200012a8, 0, 35, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200012a8, 0, 36, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200012a8, 0, 37, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200012a8, 0, 38, 26));
  NONFAILING(*(uint32_t*)0x200012b0 = 0xfffffffe);
  NONFAILING(*(uint32_t*)0x200012b4 = 0);
  NONFAILING(*(uint64_t*)0x200012b8 = 0);
  NONFAILING(*(uint64_t*)0x200012c0 = 0);
  NONFAILING(*(uint64_t*)0x200012c8 = 0);
  NONFAILING(*(uint64_t*)0x200012d0 = 0);
  NONFAILING(*(uint32_t*)0x200012d8 = 0);
  NONFAILING(*(uint32_t*)0x200012dc = 0);
  NONFAILING(*(uint64_t*)0x200012e0 = 0);
  NONFAILING(*(uint32_t*)0x200012e8 = 0);
  NONFAILING(*(uint16_t*)0x200012ec = 0);
  NONFAILING(*(uint16_t*)0x200012ee = 0);
  NONFAILING(*(uint32_t*)0x200012f0 = 0);
  NONFAILING(*(uint32_t*)0x200012f4 = 0);
  NONFAILING(*(uint64_t*)0x200012f8 = 3);
  res = syscall(__NR_perf_event_open, /*attr=*/0x20001280ul, /*pid=*/0,
                /*cpu=*/-1, /*group=*/-1, /*flags=*/0ul);
  if (res != -1)
    r[0] = res;
  syscall(__NR_mmap, /*addr=*/0x20ffd000ul, /*len=*/0x3000ul, /*prot=*/0ul,
          /*flags=*/0x11ul, /*fd=*/r[0], /*offset=*/0ul);
  syscall(__NR_open_by_handle_at, /*mountdirfd=*/-1, /*handle=*/0ul,
          /*flags=*/0x10040ul);
  syscall(__NR_socketpair, /*domain=*/1ul, /*type=*/5ul, /*proto=*/0,
          /*fds=*/0ul);
  syscall(__NR_perf_event_open, /*attr=*/0ul, /*pid=*/0, /*cpu=*/0xcul,
          /*group=*/-1, /*flags=*/8ul);
  NONFAILING(*(uint32_t*)0x20000580 = 2);
  NONFAILING(*(uint32_t*)0x20000584 = 0x80);
  NONFAILING(*(uint8_t*)0x20000588 = 1);
  NONFAILING(*(uint8_t*)0x20000589 = 0);
  NONFAILING(*(uint8_t*)0x2000058a = 0);
  NONFAILING(*(uint8_t*)0x2000058b = 0);
  NONFAILING(*(uint32_t*)0x2000058c = 0);
  NONFAILING(*(uint64_t*)0x20000590 = 0);
  NONFAILING(*(uint64_t*)0x20000598 = 0);
  NONFAILING(*(uint64_t*)0x200005a0 = 0);
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200005a8, 0, 0, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200005a8, 0, 1, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200005a8, 0, 2, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200005a8, 0, 3, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200005a8, 0, 4, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200005a8, 0, 5, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200005a8, 0, 6, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200005a8, 0, 7, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200005a8, 0, 8, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200005a8, 0, 9, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200005a8, 0, 10, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200005a8, 0, 11, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200005a8, 0, 12, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200005a8, 0, 13, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200005a8, 0, 14, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200005a8, 0, 15, 2));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200005a8, 0, 17, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200005a8, 0, 18, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200005a8, 0, 19, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200005a8, 0, 20, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200005a8, 0, 21, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200005a8, 0, 22, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200005a8, 0, 23, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200005a8, 0, 24, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200005a8, 0, 25, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200005a8, 0, 26, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200005a8, 0, 27, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200005a8, 0, 28, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200005a8, 0, 29, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200005a8, 0, 30, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200005a8, 0, 31, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200005a8, 0, 32, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200005a8, 0, 33, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200005a8, 0, 34, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200005a8, 0, 35, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200005a8, 0, 36, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200005a8, 0, 37, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200005a8, 0, 38, 26));
  NONFAILING(*(uint32_t*)0x200005b0 = 0x7fffffff);
  NONFAILING(*(uint32_t*)0x200005b4 = 0);
  NONFAILING(*(uint64_t*)0x200005b8 = 0);
  NONFAILING(*(uint64_t*)0x200005c0 = 0);
  NONFAILING(*(uint64_t*)0x200005c8 = 0);
  NONFAILING(*(uint64_t*)0x200005d0 = 0);
  NONFAILING(*(uint32_t*)0x200005d8 = 0);
  NONFAILING(*(uint32_t*)0x200005dc = 8);
  NONFAILING(*(uint64_t*)0x200005e0 = 0);
  NONFAILING(*(uint32_t*)0x200005e8 = 0);
  NONFAILING(*(uint16_t*)0x200005ec = 0x100);
  NONFAILING(*(uint16_t*)0x200005ee = 0);
  NONFAILING(*(uint32_t*)0x200005f0 = 0);
  NONFAILING(*(uint32_t*)0x200005f4 = 0);
  NONFAILING(*(uint64_t*)0x200005f8 = 0);
  syscall(__NR_perf_event_open, /*attr=*/0x20000580ul, /*pid=*/0, /*cpu=*/0ul,
          /*group=*/-1, /*flags=*/0ul);
}
int main(void)
{
  syscall(__NR_mmap, /*addr=*/0x1ffff000ul, /*len=*/0x1000ul, /*prot=*/0ul,
          /*flags=*/0x32ul, /*fd=*/-1, /*offset=*/0ul);
  syscall(__NR_mmap, /*addr=*/0x20000000ul, /*len=*/0x1000000ul, /*prot=*/7ul,
          /*flags=*/0x32ul, /*fd=*/-1, /*offset=*/0ul);
  syscall(__NR_mmap, /*addr=*/0x21000000ul, /*len=*/0x1000ul, /*prot=*/0ul,
          /*flags=*/0x32ul, /*fd=*/-1, /*offset=*/0ul);
  setup_sysctl();
  setup_cgroups();
  setup_swap();
  install_segv_handler();
  for (procid = 0; procid < 8; procid++) {
    if (fork() == 0) {
      use_temporary_dir();
      do_sandbox_none();
    }
  }
  sleep(1000000);
  return 0;
}
