// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE

#include <endian.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

uint64_t r[5] = {0xffffffffffffffff, 0xffffffffffffffff, 0x0,
                 0xffffffffffffffff, 0xffffffffffffffff};

int main(void)
{
  syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
  syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
  syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
  intptr_t res = 0;
  memcpy((void*)0x20000040, "/dev/iommu\000", 11);
  res = syscall(__NR_openat, 0xffffffffffffff9cul, 0x20000040ul, 0ul, 0ul);
  if (res != -1)
    r[0] = res;
  *(uint32_t*)0x20000000 = 0xc;
  *(uint32_t*)0x20000004 = 0;
  syscall(__NR_ioctl, r[0], 0x3b81, 0x20000000ul);
  memcpy((void*)0x20000000, "/dev/iommu\000", 11);
  res = syscall(__NR_openat, 0xffffffffffffff9cul, 0x20000000ul, 0ul, 0ul);
  if (res != -1)
    r[1] = res;
  *(uint32_t*)0x20000140 = 0xc;
  *(uint32_t*)0x20000144 = 0;
  res = syscall(__NR_ioctl, r[1], 0x3b81, 0x20000140ul);
  if (res != -1)
    r[2] = *(uint32_t*)0x20000148;
  *(uint32_t*)0x200000c0 = 0xc;
  *(uint32_t*)0x200000c4 = r[2];
  *(uint16_t*)0x200000c8 = 1;
  *(uint16_t*)0x200000ca = 0;
  syscall(__NR_ioctl, r[0], 0x3b88, 0x200000c0ul);
  *(uint32_t*)0x20000080 = 0x20;
  *(uint32_t*)0x20000084 = 1;
  *(uint64_t*)0x20000088 = -1;
  *(uint64_t*)0x20000090 = 0;
  *(uint64_t*)0x20000098 = 0x80000001;
  syscall(__NR_ioctl, r[0], 0x3b71, 0x20000080ul);
  *(uint32_t*)0x20000100 = 0x38;
  *(uint32_t*)0x20000104 = 5;
  *(uint32_t*)0x20000108 = r[2];
  *(uint32_t*)0x2000010c = 0;
  *(uint32_t*)0x20000114 = 0;
  res = syscall(__NR_ioctl, r[0], 0x3ba0, 0x20000100ul);
  if (res != -1)
    r[3] = *(uint32_t*)0x20000110;
  memcpy((void*)0x20000400, "/dev/iommu\000", 11);
  res = syscall(__NR_openat, 0xffffffffffffff9cul, 0x20000400ul, 0ul, 0ul);
  if (res != -1)
    r[4] = res;
  *(uint32_t*)0x200001c0 = 0x38;
  *(uint32_t*)0x200001c4 = 8;
  *(uint32_t*)0x200001c8 = r[3];
  *(uint32_t*)0x200001cc = 0x3d27;
  *(uint32_t*)0x200001d0 = 0;
  *(uint32_t*)0x200001d4 = 0;
  *(uint64_t*)0x200001d8 = 2;
  *(uint64_t*)0x200001e0 = 0x20000200;
  memcpy((void*)0x20000200, "qK", 2);
  *(uint32_t*)0x200001e8 = 0x10004;
  syscall(__NR_ioctl, r[4], 0x3ba0, 0x200001c0ul);
  return 0;
}
