// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE

#include <endian.h>
#include <sched.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

#ifndef __NR_memfd_create
#define __NR_memfd_create 319
#endif
#ifndef __NR_userfaultfd
#define __NR_userfaultfd 323
#endif

#define USLEEP_FORKED_CHILD (3 * 50 * 1000)

static long handle_clone_ret(long ret)
{
  if (ret != 0) {
    return ret;
  }
  usleep(USLEEP_FORKED_CHILD);
  syscall(__NR_exit, 0);
  while (1) {
  }
}

static long syz_clone(volatile long flags, volatile long stack,
                      volatile long stack_len, volatile long ptid,
                      volatile long ctid, volatile long tls)
{
  long sp = (stack + stack_len) & ~15;
  long ret = (long)syscall(__NR_clone, flags & ~CLONE_VM, sp, ptid, ctid, tls);
  return handle_clone_ret(ret);
}

uint64_t r[2] = {0xffffffffffffffff, 0xffffffffffffffff};

int main(void)
{
  syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
  syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
  syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
  intptr_t res = 0;
  memset((void*)0x200000c0, 0, 1);
  res = syscall(__NR_memfd_create, 0x200000c0ul, 0ul);
  if (res != -1)
    r[0] = res;
  syscall(__NR_mmap, 0x20ff6000ul, 0x7000ul, 0ul, 0x12ul, r[0], 0ul);
  res = syscall(__NR_userfaultfd, 1ul);
  if (res != -1)
    r[1] = res;
  *(uint64_t*)0x20000080 = 0xaa;
  *(uint64_t*)0x20000088 = 0;
  *(uint64_t*)0x20000090 = 0;
  syscall(__NR_ioctl, r[1], 0xc018aa3f, 0x20000080ul);
  *(uint64_t*)0x20000000 = 0x20ff6000;
  *(uint64_t*)0x20000008 = 0x4000;
  *(uint64_t*)0x20000010 = 6;
  *(uint64_t*)0x20000018 = 0;
  syscall(__NR_ioctl, r[1], 0xc020aa00, 0x20000000ul);
  *(uint64_t*)0x20000100 = 0x20ff7000;
  *(uint64_t*)0x20000108 = 0x3000;
  *(uint64_t*)0x20000110 = 1;
  syscall(__NR_ioctl, r[1], 0xc018aa06, 0x20000100ul);
  *(uint64_t*)0x20000140 = 0x20ff6000;
  *(uint64_t*)0x20000148 = 0x1000;
  *(uint64_t*)0x20000150 = 0;
  syscall(__NR_ioctl, r[1], 0xc020aa07, 0x20000140ul);
  syz_clone(0x1100, 0, 0, 0, 0, 0);
  return 0;
}
