// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE

#include <endian.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

#ifndef __NR_finit_module
#define __NR_finit_module 313
#endif

#define BITMASK(bf_off, bf_len) (((1ull << (bf_len)) - 1) << (bf_off))
#define STORE_BY_BITMASK(type, htobe, addr, val, bf_off, bf_len)               \
  *(type*)(addr) =                                                             \
      htobe((htobe(*(type*)(addr)) & ~BITMASK((bf_off), (bf_len))) |           \
            (((type)(val) << (bf_off)) & BITMASK((bf_off), (bf_len))))

uint64_t r[2] = {0xffffffffffffffff, 0xffffffffffffffff};

int main(void)
{
  syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
  syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
  syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
  intptr_t res = 0;
  *(uint32_t*)0x200004c0 = 2;
  *(uint32_t*)0x200004c4 = 0x80;
  *(uint8_t*)0x200004c8 = 1;
  *(uint8_t*)0x200004c9 = 0;
  *(uint8_t*)0x200004ca = 0;
  *(uint8_t*)0x200004cb = 0;
  *(uint32_t*)0x200004cc = 0;
  *(uint64_t*)0x200004d0 = 0;
  *(uint64_t*)0x200004d8 = 0x15111;
  *(uint64_t*)0x200004e0 = 0;
  STORE_BY_BITMASK(uint64_t, , 0x200004e8, 0, 0, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200004e8, 0, 1, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200004e8, 0, 2, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200004e8, 0, 3, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200004e8, 0, 4, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200004e8, 0, 5, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200004e8, 0, 6, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200004e8, 0, 7, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200004e8, 0, 8, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200004e8, 0, 9, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200004e8, 0, 10, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200004e8, 0, 11, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200004e8, 0, 12, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200004e8, 0, 13, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200004e8, 0, 14, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200004e8, 0, 15, 2);
  STORE_BY_BITMASK(uint64_t, , 0x200004e8, 0, 17, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200004e8, 0, 18, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200004e8, 0, 19, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200004e8, 0, 20, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200004e8, 0, 21, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200004e8, 0, 22, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200004e8, 0, 23, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200004e8, 0, 24, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200004e8, 0, 25, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200004e8, 0, 26, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200004e8, 0, 27, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200004e8, 0, 28, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200004e8, 0, 29, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200004e8, 0, 30, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200004e8, 0, 31, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200004e8, 0, 32, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200004e8, 0, 33, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200004e8, 0, 34, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200004e8, 0, 35, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200004e8, 0, 36, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200004e8, 0, 37, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200004e8, 0, 38, 26);
  *(uint32_t*)0x200004f0 = 0;
  *(uint32_t*)0x200004f4 = 0;
  *(uint64_t*)0x200004f8 = 0;
  *(uint64_t*)0x20000500 = 0;
  *(uint64_t*)0x20000508 = 0;
  *(uint64_t*)0x20000510 = 4;
  *(uint32_t*)0x20000518 = 0;
  *(uint32_t*)0x2000051c = 0;
  *(uint64_t*)0x20000520 = 0;
  *(uint32_t*)0x20000528 = 0;
  *(uint16_t*)0x2000052c = 0;
  *(uint16_t*)0x2000052e = 0;
  *(uint32_t*)0x20000530 = 0;
  *(uint32_t*)0x20000534 = 0;
  *(uint64_t*)0x20000538 = 0;
  syscall(__NR_perf_event_open, 0x200004c0ul, -1, 0ul, -1, 0ul);
  *(uint32_t*)0x200004c0 = 2;
  *(uint32_t*)0x200004c4 = 0x80;
  *(uint8_t*)0x200004c8 = 1;
  *(uint8_t*)0x200004c9 = 0;
  *(uint8_t*)0x200004ca = 0;
  *(uint8_t*)0x200004cb = 0;
  *(uint32_t*)0x200004cc = 0;
  *(uint64_t*)0x200004d0 = 0;
  *(uint64_t*)0x200004d8 = 0x15111;
  *(uint64_t*)0x200004e0 = 0;
  STORE_BY_BITMASK(uint64_t, , 0x200004e8, 0, 0, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200004e8, 0, 1, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200004e8, 0, 2, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200004e8, 0, 3, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200004e8, 0, 4, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200004e8, 0, 5, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200004e8, 0, 6, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200004e8, 0, 7, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200004e8, 0, 8, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200004e8, 0, 9, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200004e8, 0, 10, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200004e8, 0, 11, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200004e8, 0, 12, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200004e8, 0, 13, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200004e8, 0, 14, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200004e8, 0, 15, 2);
  STORE_BY_BITMASK(uint64_t, , 0x200004e8, 0, 17, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200004e8, 0, 18, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200004e8, 0, 19, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200004e8, 0, 20, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200004e8, 0, 21, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200004e8, 0, 22, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200004e8, 0, 23, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200004e8, 0, 24, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200004e8, 0, 25, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200004e8, 0, 26, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200004e8, 0, 27, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200004e8, 0, 28, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200004e8, 0, 29, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200004e8, 0, 30, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200004e8, 0, 31, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200004e8, 0, 32, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200004e8, 0, 33, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200004e8, 0, 34, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200004e8, 0, 35, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200004e8, 0, 36, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200004e8, 0, 37, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200004e8, 0, 38, 26);
  *(uint32_t*)0x200004f0 = 0;
  *(uint32_t*)0x200004f4 = 0;
  *(uint64_t*)0x200004f8 = 0;
  *(uint64_t*)0x20000500 = 0;
  *(uint64_t*)0x20000508 = 0;
  *(uint64_t*)0x20000510 = 4;
  *(uint32_t*)0x20000518 = 0;
  *(uint32_t*)0x2000051c = 0;
  *(uint64_t*)0x20000520 = 0;
  *(uint32_t*)0x20000528 = 0;
  *(uint16_t*)0x2000052c = 0;
  *(uint16_t*)0x2000052e = 0;
  *(uint32_t*)0x20000530 = 0;
  *(uint32_t*)0x20000534 = 0;
  *(uint64_t*)0x20000538 = 0;
  syscall(__NR_perf_event_open, 0x200004c0ul, -1, 0ul, -1, 0ul);
  syscall(__NR_finit_module, -1, 0ul, 0ul);
  syscall(__NR_openat, 0xffffff9c, 0ul, 0x147942ul, 0ul);
  memcpy((void*)0x20000040, "./file1\000", 8);
  res = syscall(__NR_openat, 0xffffff9c, 0x20000040ul, 0x143942ul, 0ul);
  if (res != -1)
    r[0] = res;
  *(uint8_t*)0x20000640 = 0xfc;
  *(uint8_t*)0x20000641 = 1;
  memset((void*)0x20000642, 0, 13);
  *(uint8_t*)0x2000064f = 1;
  *(uint32_t*)0x20000650 = htobe32(-1);
  *(uint16_t*)0x20000660 = htobe16(0x4e21);
  *(uint16_t*)0x20000662 = htobe16(0x1000);
  *(uint16_t*)0x20000664 = htobe16(0x4e24);
  *(uint16_t*)0x20000666 = htobe16(9);
  *(uint16_t*)0x20000668 = 2;
  *(uint8_t*)0x2000066a = 0;
  *(uint8_t*)0x2000066b = 0xa0;
  *(uint8_t*)0x2000066c = 0x3c;
  *(uint32_t*)0x20000670 = 0;
  *(uint32_t*)0x20000674 = 0;
  *(uint64_t*)0x20000678 = 1;
  *(uint64_t*)0x20000680 = 6;
  *(uint64_t*)0x20000688 = 5;
  *(uint64_t*)0x20000690 = 0x4162;
  *(uint64_t*)0x20000698 = 0;
  *(uint64_t*)0x200006a0 = 0x7fffffff;
  *(uint64_t*)0x200006a8 = 0x7ff;
  *(uint64_t*)0x200006b0 = 0x3f;
  *(uint64_t*)0x200006b8 = 0;
  *(uint64_t*)0x200006c0 = 9;
  *(uint64_t*)0x200006c8 = 0x100000000;
  *(uint64_t*)0x200006d0 = 0x222a27c7;
  *(uint32_t*)0x200006d8 = 4;
  *(uint32_t*)0x200006dc = 0x6e6bb4;
  *(uint8_t*)0x200006e0 = 1;
  *(uint8_t*)0x200006e1 = 0;
  *(uint8_t*)0x200006e2 = 0;
  *(uint8_t*)0x200006e3 = 2;
  *(uint8_t*)0x200006e8 = 0xfe;
  *(uint8_t*)0x200006e9 = 0x80;
  memset((void*)0x200006ea, 0, 13);
  *(uint8_t*)0x200006f7 = 0xbb;
  *(uint32_t*)0x200006f8 = htobe32(0x4d2);
  *(uint8_t*)0x200006fc = 0x32;
  *(uint16_t*)0x20000700 = 0xa;
  *(uint8_t*)0x20000704 = -1;
  *(uint8_t*)0x20000705 = 1;
  memset((void*)0x20000706, 0, 13);
  *(uint8_t*)0x20000713 = 1;
  *(uint32_t*)0x20000714 = 0x3500;
  *(uint8_t*)0x20000718 = 2;
  *(uint8_t*)0x20000719 = 0;
  *(uint8_t*)0x2000071a = 0xdb;
  *(uint32_t*)0x2000071c = 0x10000;
  *(uint32_t*)0x20000720 = 5;
  *(uint32_t*)0x20000724 = 0x80000000;
  syscall(__NR_setsockopt, -1, 0x29, 0x23, 0x20000640ul, 0xe8ul);
  syscall(__NR_pread64, r[0], 0ul, 0ul, 9ul);
  syscall(__NR_ioctl, -1, 0x40806685, 0ul);
  syscall(__NR_fallocate, r[0], 0ul, 0x1000001ul, 0x55ul);
  res = syscall(__NR_openat, 0xffffff9c, 0ul, 0x147942ul, 0ul);
  if (res != -1)
    r[1] = res;
  syscall(__NR_sendfile, r[1], r[1], 0ul, 0x10004b4ul);
  *(uint32_t*)0x20000440 = 5;
  *(uint32_t*)0x20000444 = 0x80;
  *(uint8_t*)0x20000448 = 0x2b;
  *(uint8_t*)0x20000449 = 0x15;
  *(uint8_t*)0x2000044a = 7;
  *(uint8_t*)0x2000044b = 4;
  *(uint32_t*)0x2000044c = 0;
  *(uint64_t*)0x20000450 = 0xd1;
  *(uint64_t*)0x20000458 = 0x45180;
  *(uint64_t*)0x20000460 = 1;
  STORE_BY_BITMASK(uint64_t, , 0x20000468, 1, 0, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000468, 1, 1, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000468, 1, 2, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000468, 0, 3, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000468, 0, 4, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000468, 1, 5, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000468, 1, 6, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000468, 0, 7, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000468, 1, 8, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000468, 0, 9, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000468, 0, 10, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000468, 1, 11, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000468, 1, 12, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000468, 0, 13, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000468, 1, 14, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000468, 0, 15, 2);
  STORE_BY_BITMASK(uint64_t, , 0x20000468, 0, 17, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000468, 1, 18, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000468, 1, 19, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000468, 0, 20, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000468, 0, 21, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000468, 1, 22, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000468, 1, 23, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000468, 0, 24, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000468, 0, 25, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000468, 1, 26, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000468, 1, 27, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000468, 1, 28, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000468, 0, 29, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000468, 0, 30, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000468, 1, 31, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000468, 0, 32, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000468, 0, 33, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000468, 0, 34, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000468, 0, 35, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000468, 0, 36, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000468, 1, 37, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000468, 0, 38, 26);
  *(uint32_t*)0x20000470 = 7;
  *(uint32_t*)0x20000474 = 4;
  *(uint64_t*)0x20000478 = 0x20000000;
  *(uint64_t*)0x20000480 = 0;
  *(uint64_t*)0x20000488 = 0x2040;
  *(uint64_t*)0x20000490 = 0x9090;
  *(uint32_t*)0x20000498 = 0xff;
  *(uint32_t*)0x2000049c = 1;
  *(uint64_t*)0x200004a0 = 1;
  *(uint32_t*)0x200004a8 = 0x80000001;
  *(uint16_t*)0x200004ac = 0x200;
  *(uint16_t*)0x200004ae = 0;
  *(uint32_t*)0x200004b0 = 1;
  *(uint32_t*)0x200004b4 = 0;
  *(uint64_t*)0x200004b8 = 8;
  syscall(__NR_perf_event_open, 0x20000440ul, r[1], 0xdul, r[0], 0xdul);
  return 0;
}
